Exception during training: 'History' object has no attribute 'save'
Traceback (most recent call last):
  File "<ipython-input-21-5fc0d3a82976>", line 11, in train
    classifier.save(os.path.join(model_path, 'pd.h5'))
AttributeError: 'History' object has no attribute 'save'
